### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by kelonye** [mafintosh/docker-registry-server#8]
Currently at v1.2.0

**Comment by mafintosh** [comment]
2.1.1 is pushed to the docker registry now. thanks for bringing it to my attention

**Comment by mcollina** [comment]
I think we should set up an automated build.

**Comment by kelonye** [comment]
:awesome:

**Comment by mafintosh** [comment]
@mcollina can we do that on travis?

**Comment by mcollina** [comment]
You can't do it on Travis, but you can do it straight from Docker Hub: http://docs.docker.com/docker-hub/builds/
